import collect from "collect.js";

export default collect([
    {step: "C", alter: 0, circleId: 0, type: "maj", scoreAlter: 0},
    {step: "G", alter: 0, circleId: 1, type: "maj", scoreAlter: 1},
    {step: "D", alter: 0, circleId: 2, type: "maj", scoreAlter: 2},
    {step: "A", alter: 0, circleId: 3, type: "maj", scoreAlter: 3},
    {step: "E", alter: 0, circleId: 4, type: "maj", scoreAlter: 4},
    {step: "B", alter: 0, circleId: 5, type: "maj", scoreAlter: 5},
    {step: "C", alter: -1, circleId: 5, type: "maj", scoreAlter: -7},
    {step: "F", alter: 1, circleId: 6, type: "maj", scoreAlter: 6},
    {step: "G", alter: -1, circleId: 6, type: "maj", scoreAlter: -6},
    {step: "C", alter: 1, circleId: 7, type: "maj", scoreAlter: 7},
    {step: "D", alter: -1, circleId: 7, type: "maj", scoreAlter: -5},
    {step: "A", alter: -1, circleId: 8, type: "maj", scoreAlter: -4},
    {step: "E", alter: -1, circleId: 9, type: "maj", scoreAlter: -3},
    {step: "B", alter: -1, circleId: 10, type: "maj", scoreAlter: -2},
    {step: "F", alter: 0, circleId: 11, type: "maj", scoreAlter: -1},
    {step: "A", alter: 0, circleId: 0, type: "min", scoreAlter: 0},
    {step: "E", alter: 0, circleId: 1, type: "min", scoreAlter: 1},
    {step: "B", alter: 0, circleId: 2, type: "min", scoreAlter: 2},
    {step: "F", alter: 1, circleId: 3, type: "min", scoreAlter: 3},
    {step: "C", alter: 1, circleId: 4, type: "min", scoreAlter: 4},
    {step: "G", alter: 1, circleId: 5, type: "min", scoreAlter: 5},
    {step: "E", alter: -1, circleId: 6, type: "min", scoreAlter: -6},
    {step: "B", alter: -1, circleId: 7, type: "min", scoreAlter: -5},
    {step: "F", alter: 0, circleId: 8, type: "min", scoreAlter: -4},
    {step: "C", alter: 0, circleId: 9, type: "min", scoreAlter: -3},
    {step: "G", alter: 0, circleId: 10, type: "min", scoreAlter: -2},
    {step: "D", alter: 0, circleId: 11, type: "min", scoreAlter: -1},
])