jobs:
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install and Build
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install -g pnpm --force
          pnpm config set strict-peer-dependencies false
          pnpm config set auto-install-peers true 
          pnpm install --no-frozen-lockfile
          pnpm build
        env:
          NODE_ENV: production
          CI: true
          VITE_GITHUB_PAGES: true

      - name: Deploy to GitHub Pages with peaceiris/action-gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: docs
